name: school_management
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.7.7
  cloud_functions: ^4.7.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  file_picker: ^8.0.5
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  equatable: ^2.0.5
  flutter_stripe: ^10.2.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  csv: ^6.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  firebase_messaging: ^14.6.7
  provider: ^6.0.0
  shared_preferences: ^2.5.3
  async_notifier: ^0.5.0
  pdf: ^3.11.3
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/school_logo.png"
  adaptive_icon_background: "#005A9C"
  adaptive_icon_foreground: "images/school_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/fonts/