// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNV7CbHTaIbkQ2hi0Jwk0HZCq5IrdsIw',
    appId: '1:1087394897321:web:bf6e0b37dd98ef3c3578b8',
    messagingSenderId: '1087394897321',
    projectId: 'school-mang-ivar',
    authDomain: 'school-mang-ivar.firebaseapp.com',
    databaseURL: 'https://school-mang-ivar-default-rtdb.firebaseio.com',
    storageBucket: 'school-mang-ivar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtYuooK754EKjzUp6gFqdPR_DKJpKnMI',
    appId: '1:1087394897321:android:409853738481ef383578b8',
    messagingSenderId: '1087394897321',
    projectId: 'school-mang-ivar',
    databaseURL: 'https://school-mang-ivar-default-rtdb.firebaseio.com',
    storageBucket: 'school-mang-ivar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVuJOWUUVSKSB_Uwdzd8wLzdvymMP0Eg',
    appId: '1:1087394897321:ios:e9726e53e8a949853578b8',
    messagingSenderId: '1087394897321',
    projectId: 'school-mang-ivar',
    databaseURL: 'https://school-mang-ivar-default-rtdb.firebaseio.com',
    storageBucket: 'school-mang-ivar.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVuJOWUUVSKSB_Uwdzd8wLzdvymMP0Eg',
    appId: '1:1087394897321:ios:e9726e53e8a949853578b8',
    messagingSenderId: '1087394897321',
    projectId: 'school-mang-ivar',
    databaseURL: 'https://school-mang-ivar-default-rtdb.firebaseio.com',
    storageBucket: 'school-mang-ivar.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNV7CbHTaIbkQ2hi0Jwk0HZCq5IrdsIw',
    appId: '1:1087394897321:web:e8aae5171ed6aa463578b8',
    messagingSenderId: '1087394897321',
    projectId: 'school-mang-ivar',
    authDomain: 'school-mang-ivar.firebaseapp.com',
    databaseURL: 'https://school-mang-ivar-default-rtdb.firebaseio.com',
    storageBucket: 'school-mang-ivar.firebasestorage.app',
  );

}